### ISSUE TITLE
Slurm : partition time limit

### ISSUE THREAD

**Issue by MbDiop** [tdayris-perso/rna-dge-salmon-deseq2#1]
The pipeline stopped at the begining on a slurm cluster because a job is blocked in pending state with reason "partitionTimeLimit".
```
[Wed Oct  7 16:54:48 2020]
Job 22: Copying reference genome annotaion
Reason: Missing output files: genomes/gencode.v34.basic.annotation.filtered.gtf

Submitted job 22 with external jobid 'Submitted batch job 900220'.

**Comment by MbDiop** [comment]
To resolve this issue I had to decrease the `time_min` in the file `rules/copy.smk` .

**Comment by tdayris-perso** [comment]
Solution provided at: https://github.com/tdayris-perso/rna-dge-salmon-deseq2/wiki/Frequently_Asked_Questions#slurm--partition-time-limit-error

Reducing time_min in copy rules will lead to errors when the fliesystem is under pressure.
